version: "3.8"

services:
  wisest-postgres:
    container_name: postgres
    image: postgres:17.4
    volumes:
      - "./postgres_password:/postgres_password"
      - "./initial_data:/docker-entrypoint-initdb.d"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=wisest
      - POSTGRES_PASSWORD_FILE=/postgres_password
    ports:
      - "5432:5432"
    networks:
      - databasenetwork

  wisest-pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.2.0
    depends_on:
      - wisest-postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=True
    ports:
      - "5050:80"
    networks:
      - databasenetwork

networks:
  databasenetwork:
    driver: bridge
